### ISSUE TITLE
failed to build due to python3-apt package missing

### ISSUE THREAD

**Issue by Eliatrope38** [lueschem/edi-var#3]
Hello,
I try to build without any modification, but I'm facing this error
[WARNING]: Updating cache and auto-installing missing dependency: python3-apt
fatal: [edi-tmp-64928cb510fe1a1276d0]: FAILED! => {"changed": false, "cmd": "apt-get install --no-install-recommends python3-apt -y -q", "msg": "E: Package 'python3-apt' has no installation candidate", "rc": 100, "stderr": "E: Package 'python3-apt' has no installation candidate\n", "stderr_lines": ["E: Package 'python3-apt' has no installation candidate"], "stdout": "Reading package lists...\nBuilding dependency tree...\nPackage python3-apt is not available, but is referred to by another package.\nThis may mean that the package is missing, has been obsoleted, or\nis only available from another source\n\n", "stdout_lines": ["Reading package lists...", "Building dependency tree...", "Package python3-apt is not available, but is referred to by another package.", "This may mean that the package is missing, has been obsoleted, or", "is only available from another source", ""]}

how to fix that ?

Thank you

**Comment by lueschem** [comment]
At this stage Ansible tries to install the python3-apt Debian package within the LXD container edi-tmp-64928cb510fe1a1276d0. However, this fails because most likely the network cannot be reached from within the edi-tmp-64928cb510fe1a1276d0 container. Just on the previous stage the network was also required in order to do the debootstrapping of the minimal root file system. So in general networking does work but not from within the LXD container.
The last time I saw this I was hit by a faulty iptables setup done by Docker. Does it somehow look similar to
[this issue](https://discuss.linuxcontainers.org/t/cant-get-ipv4-addresses-with-docker-installed/8019)?

**Comment by Eliatrope38** [comment]
sorry for delay, yes you right network is not reachable from into the container
thank you
