### ISSUE TITLE
Modifications for VAR-SOM-iMX8M-MINI

### ISSUE THREAD

**Issue by mfaccin** [lueschem/edi-var#4]
Hi, guys. Sorry for the beginner question but I'm not used to cross-compile/building embedded images in complex environments. 
Could you guide me on how hard and what should I adopt in order to use your repo?

I'm currently using a Debian bullseye and would like to use Mender for OTA as you did. Thanks!

**Comment by lueschem** [comment]
Hi Mauricio

The VAR-SOM-MX8M-MINI is pretty similar to the VAR-SOM-MX8M-NANO. So you could take (clone/fork) the edi-var setup as a starting point and adjust or extend it according to the needs of the VAR-SOM-MX8M-MINI.
I have described a similar procedure for the [Raspberry Pi 4](https://www.get-edi.io/Getting-Started-with-a-new-Embedded-System/).
I guess that you are currently running the Debian bullseye image provided by Variscite. Variscite has a [very good documentation](https://variwiki.com/index.php?title=Debian_Build_Release&release=RELEASE_BULLSEYE_V2.0_DART-MX8M-MINI) and it is extremely valuable as a starting point. They also publish the [source code](https://github.com/varigit/debian-var/tree/debian_bullseye_var01) of the tools they use to build their images. The most tricky part is the [bootloader adjustment](https://github.com/lueschem/edi-boot-shim) so that it is suitable for the chosen setup (including Mender). The good thing is that you already have a working setup and this lets you figure out what kind of adjustments are needed.
The kernel then might be the first thing you want to cross compile. [Here is how I did it for the VAR-SOM-MX8M-NANO](https://github.com/lueschem/edi-var/blob/master/docs/kernel_build.md). For the edi-boot-shim and the kernel Debian package it is then convenient if you have your own Debian package repository (either self hosted or e.g. [packagecloud](https://packagecloud.io/)).
As you can see the overall process is unfortunately way more complicated than installing Debian on a standard amd64 machine. But with the good documentation from Variscite it is absolutely doable and do not hesitate to ask if you have some concrete questions.

Best regards
Matthias
